name: "Marie Hooper"
description: "Portfolio Site for Marie Hooper"

url: "https://mariehooper.me"

#paginate: 10

permalink: pretty

sass:
  style: :compressed
collections:
  home:
    output: false
  projects:
    output: true
    permalink: /projects/:title/

gems:
  - jekyll-sitemap
