name: "Marie Hooper"
description: "Portfolio Site for Marie Hooper"

url: "http://localhost:4000"

#paginate: 10

permalink: pretty

sass:
  style: :compressed
collections:
  home:
    output: false
  projects:
    output: true
    permalink: /projects/:title/
