name: "Marie Hooper"
description: "Portfolio Site for Marie Hooper"

url: "http://marie.hoopr.io"

#paginate: 10

markdown: rdiscount
permalink: pretty

sass:
  style: :compressed
collections:
  home:
    output: false
  projects:
    output: true
    permalink: /projects/:title/
